Add file_env support
Add file environment support for admin password
Will enable using secrets with docker swarm

diff --git a/install/etc/cont-init.d/30-fusiondirectory b/install/etc/cont-init.d/30-fusiondirectory
--- a/install/etc/cont-init.d/30-fusiondirectory
+++ b/install/etc/cont-init.d/30-fusiondirectory
@@ -1,5 +1,23 @@
 #!/usr/bin/with-contenv bash
 
+function file_env () {
+		local var="$1"
+		local fileVar="${var}_FILE"
+		local def="${2:-}"
+		local val="$def"
+		if [ "${!fileVar:-}" ]; then
+			val="$(<"${!fileVar}")"
+		elif [ "${!var:-}" ]; then
+			val="${!var}"
+		fi
+		if [ -z ${val} ]; then
+			echo >&2 "error: neither $var nor $fileVar are set but are required"
+			exit 1
+		fi
+		export "$var"="$val"
+		unset "$fileVar"
+	}
+
 for s in /assets/functions/*; do source $s; done
 PROCESS_NAME="fusiondirectory"
 
@@ -352,6 +370,8 @@ EOF
       LDAP_NAME=LDAP${i}_NAME
       LDAP_TLS=LDAP${i}_TLS
       LDAP_PORT=LDAP${i}_PORT
+      
+      file_env 'LDAP_ADMIN_PASS'
 
       if [ "${!LDAP_TLS}" = "TRUE" ] ; then
           LDAP_SCHEME="ldaps"
